Repository pvsaintpe/yii2-search, pull requests merged in 2019-03, with the labels that each got.

#7 WIP: No calc columns
  interfaces/CalcInterface.php
  traits/CalcTrait.php
  traits/SearchTrait.php
Labels: enhancement

#8 no calc columns
  interfaces/CalcInterface.php
  traits/CalcTrait.php
  traits/SearchTrait.php
Labels: enhancement

#9 Expression sort
  traits/SearchTrait.php
Labels: bug, enhancement

#11 Add expression attributes
  traits/SearchTrait.php
Labels: bug, enhancement

#12 fixes
  traits/SearchTrait.php
Labels: bug, enhancement

#13 Fix
  traits/SearchTrait.php
Labels: bug

#15 New structure
  components/ActiveQuery.php
  traits/ExpressionTrait.php
  traits/RelationTrait.php
  traits/SearchTrait.php
Labels: bug, enhancement

#16 expression refactoring
  components/ActiveQuery.php
  traits/ExpressionTrait.php
  traits/RelationTrait.php
  traits/SearchTrait.php
Labels: bug, enhancement

#17 tt
  traits/ExpressionTrait.php
Labels: bug

#19 Fix RelationTrait
  traits/RelationTrait.php
Labels: bug, enhancement

#20 fix relation trait
  traits/RelationTrait.php
Labels: bug, enhancement

#21 Fix
  traits/RelationTrait.php
Labels: bug, enhancement

#24 Empty attributes in relations
  traits/RelationTrait.php
Labels: bug

#25 fix bugs
  traits/RelationTrait.php
Labels: bug

#26 Fix RelationTrait
  traits/RelationTrait.php
Labels: bug, enhancement

#28 Fix cur relations
  traits/RelationTrait.php
Labels: bug
